<a href="https://colab.research.google.com/github/MJZ-Hossen/phitronio_Ai_Ml/blob/main/M10_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##** M10.2**- ndarray and its attributes


In [19]:
arr=[1,2,3]
print(5*arr)


[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


### Nd arry

In [20]:
import numpy as np

#1d arry
arr1= np.array([1,2,3,4,5,])
#2d list
arr2 =np.array([
    [1,2,3],
    [4,5,6]
])

#3d array
arr3 =np.array([
    [ [1,2,3],
     [4,5,6],
    [14,15,16]],

   [[7,8,9],
    [11,12,13],
    [14,15,16]],

    [[7,8,9],
    [11,12,13],
    [14,15,16]]
              ] )
## Array attribute
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr3)

1
2
3
(5,)
(2, 3)
(3, 3, 3)
int64
int64
int64
5
6
27
[[[ 1  2  3]
  [ 4  5  6]
  [14 15 16]]

 [[ 7  8  9]
  [11 12 13]
  [14 15 16]]

 [[ 7  8  9]
  [11 12 13]
  [14 15 16]]]


### Ndarray data type

In [21]:
import numpy as np
arr = np.array([1,2,3.2])
# upcasted to float
print(arr.dtype)

#upcasted to string
arr = np.array([1,2,3.2,'hello'])
print(arr.dtype)


arr = np.array([1,True,3.25,'hello',])
print(arr.dtype)



float64
<U32
<U32


In [22]:
import numpy as np
#extra
# Creating a 3x3 int32 array of zeros
arr2 = np.zeros((3, 123456789123), dtype=np.int32)
print(arr2.dtype)
arr2 = np.zeros((3, 123456789123), dtype=np.int16)
print(arr2.dtype)

arr4 = np.array([1,2,300],dtype=np.int16)
print(arr4.dtype)
print(arr4)

#using .astype to change the data type of an array, Series, or DataFrame
arr4= arr4.astype(np.int32)
print(arr4.dtype)

#error
arr = np.array([1,2,3.2,'hello'],dtype=np.float64)

int32
int16
int16
[  1   2 300]
int32


ValueError: could not convert string to float: 'hello'

### ndarray creation from existing data

In [36]:
#set
st = { 1, 2, 3 }
arr= np.array(st)
print(arr)  ##{1, 2, 3}
print(arr.dtype)

''' so the type of set can not be changed because the whole set works as an object or as a whole....
as we can not access the individual elements of a set.
To do that we need to convert the set to a list or tuple first.
'''
## arr = arr.astype(np.int32)
## TypeError: int() argument must be a string, a bytes-like object or a real number, not 'set'

arr= np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


{1, 2, 3}
object
[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [37]:
#dictionary
dc = { 'a': 10 , 'b' : 20 , 'c' :30 } #kind of  set '''object '''

keys = dc.keys()   #dict_keys(['a', 'b', 'c'])
values = dc.values()
items = dc.items()

## print(arr.dtype)
'''object '''


#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [38]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [39]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


### Creating ndarray from scratch

In [23]:
#zeros
import numpy as np
arr5 =np.array([
    [ [1,2,3],
     [4,5,6],
    [14,15,16]],

   [[7,8,9],
    [11,12,13],
    [14,15,16]],

    [[7,8,9],
    [11,12,13],
    [14,15,16]]
              ] )

arr = np.zeros_like(arr5) ## arr5 shape same ...look at the top of this chart
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [24]:
#np.ones
arr = np.ones((3,4,3),dtype=np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



arr = np.ones_like(arr5) ## arr3 shape same
print(arr)
print(arr.shape)


[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
(3, 3, 3)


In [25]:
#np.empty
arr = np.empty((4,3),dtype=np.int8)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

''' here it will taKe junk value from memory. so the output will be random'''
arr = np.empty_like(arr5) ## arr3 shape same
print(arr)
print(arr.shape)

[[  38 -107   -9]
 [  27    0    0]
 [   0    0    0]
 [   0    0    0]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
(3, 3, 3)


In [26]:
#np.full
arr = np.full((4,3),10)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

arr = np.full((4,3),np.inf)
print(arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
<class 'numpy.ndarray'>
int64
(4, 3)
2
12
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]


In [27]:
#10.6
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)


[[0.59705024 0.68382868 0.71587241]
 [0.04794353 0.60652571 0.98856585]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6
[[3 1 8]
 [8 6 1]]


# M10.8 : Matrix for linear algebra

In [28]:
import numpy as np
diagonal_matrix = np.diag([1,2,3,4])

print(diagonal_matrix)
print(diagonal_matrix.shape)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)


In [29]:
# identity matrix

identity_mat = np.eye(4)
# print(identity_mat)
# print(identity_mat.shape)


# np.eye(row , column,k) here k is the step to shift a place of identity values

mat = np.eye(3,4)
print(mat)

mat = np.eye(3,4,1)
print(mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## M10.9 :Indexing and slicing

In [30]:
#indexing
import numpy as np
#1d arry
arr1= np.array([1,2,3,4,5,])
#2d list
arr2 =np.array([
    [1,2,3],
    [4,5,6]
])
arr1[2]=100

print(arr1)
print(arr2)

print(arr1[2])
print(arr2[1][2])

[  1   2 100   4   5]
[[1 2 3]
 [4 5 6]]
100
6


In [31]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod)
print(arr1)

[  2 100 200]
[  1   2 100   4   5]


In [32]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


In [33]:

# iteration
for i in np.nditer(arr2):
    print(i)

1
2
3
4
5
6


# M11_ Data analysis with Numpy 2